# Generated by Django 5.1.6 on 2025-03-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('storage_temp', models.CharField(blank=True, max_length=50)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medicines.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medicines', models.ManyToManyField(to='medicines.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(choices=[('1 tablet', '1 tablet'), ('2 tablets', '2 tablets'), ('3 tablets', '3 tablets'), ('5 ml', '5 ml'), ('10 ml', '10 ml'), ('15 ml', '15 ml'), ('1 capsule', '1 capsule'), ('2 capsules', '2 capsules'), ('3 capsules', '3 capsules')], default='1 tablet', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('remaining_doses', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.usermedicine')),
            ],
        ),
    ]
