# Generated by Django 5.1.6 on 2025-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedicine',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermedicine',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
