# Generated by Django 5.1.6 on 2025-02-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_usermedicine_day_alter_usermedicine_time'),
    ]

    operations = [
    ]
